[build.targets.wheel]
only-include = ["src/pydra/tasks/fsl"]
sources = ["src"]

[envs.default]
dependencies = ["pytest"]
[envs.default.scripts]
test = "pytest {args}"

[[envs.default.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
  "black",
  "isort",
  "tomli",
]
[envs.lint.scripts]
all = [
  "black --check --diff {args:src}",
  "isort --check --diff {args:src}",
]
fix = [
  "black --quiet {args:src}",
  "isort --quiet {args:src}",
]

[envs.docs]
template = "docs"
dependencies = [
  "pydata-sphinx-theme >=0.13",
  "sphinx <7",
  "sphinx-autobuild",
  "sphinx-pyproject",
]
[envs.docs.scripts]
build = "sphinx-build docs docs/_build/html -b {args:html}"
serve = "sphinx-autobuild docs docs/_build/html {args}"
